language: generic

sudo: false
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++
            - gfortran
            - gromacs

matrix:
  include:
    - { os: linux, env: PYTHON_VERSION=2.7 }
    - { os: linux, env: PYTHON_VERSION=3.6 MINIMAL_PACKAGES=yes }
    - { os: linux, env: PYTHON_VERSION=3.5 }
    - { os: linux, env: PYTHON_VERSION=pypy }
#   - { os: osx, env: PYTHON_VERSION=3.4 MINIMAL_PACKAGES=yes }

install:
    - source devtools/ci/travis/install.sh
    - pip install .
    - python -c "import parmed; print(parmed.__version__)"
    - source devtools/ci/travis/runtest.sh
